package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Alert generated by AI agent or monitoring system
type Alert struct {
	ID           primitive.ObjectID `json:"id,omitempty" bson:"_id,omitempty"`
	StationID    string             `json:"station_id" bson:"station_id"`
	IMEI         string             `json:"imei" bson:"imei"`
	Type         string             `json:"type" bson:"type"`
	Severity     string             `json:"severity" bson:"severity"`
	Message      string             `json:"message" bson:"message"`
	AIAnalysis   string             `json:"ai_analysis" bson:"ai_analysis"`
	Acknowledged bool               `json:"acknowledged" bson:"acknowledged"`
	CreatedAt    time.Time          `json:"created_at" bson:"created_at"`
}
